### ISSUE TITLE
Use ovn-nbctl --wait hv to get end-to-end port binding time

### ISSUE THREAD

**Issue by hzhou8** [openvswitch/ovn-scale-test#97]
Currently the scale testing waits port state UP in ovn-nb and then starts next round of port creation and binding. This is inaccurate, because when CPU is 100% in test farms it can't reflect the real time that ovn-controllers spent to complete each round of processing. 

With the new feature "--wait hv" [1], we can now wait for the port bindings to be processed and reflected on all HVs before starting next round, so that the real processing time can be reflected and get more accurate result of port-binding performance.

[1] https://github.com/openvswitch/ovs/commit/fa183acc654f7e5da17cd70fc91d6b5b02782183

**Comment by huikang** [comment]
@hzhou8 would you mind being assigned of this task? Thanks.

**Comment by huikang** [comment]
@hzhou8 the commit message of this feature says
`With --wait=sb, ovn-nbctl now waits for ovn-northd
to update the southbound database; with --wait=hv, it waits for the
changes to make their way to Open vSwitch on every hypervisor.`

However, ovn-scale-test uses "ovs-vsctl" command to bind the logical port
to br-int on the hypervisor, instead of ovn-nbctl. Could you clarify that at which step, shall we
add "--wait hv" in ovn-scale-test? Thanks.

**Comment by hzhou8** [comment]
@huikang yes this is a little bit tricky because port binding with ovs-vsctl happens on HV, which doesn't change ovn-nb directly. Instead, it is ovn-controller detect the port-binding and then update the ovn-sb, which is then detected by ovn-northd which updates the port state in ovn-nb. 

So instead of making a change by ovn-nbctl and waiting for the HVs to catch up, we use wait-until to wait for port state become up (this behavior doesn't change), and then use "ovn-nbctl --wait=hv sync" to wait for the port state change to be processed on all HVs.

I submitted a pull request [1] for this. Please kindly review. Thanks!

[1] https://github.com/openvswitch/ovn-scale-test/pull/120

**Comment by huikang** [comment]
@hzhou8 can we close this issue now as the PR has been merged? Thanks.

**Comment by hzhou8** [comment]
Yes :)
